In [3]:
import pandas as pd #data processing
import numpy as np #arithmetic operation

from IPython.display import display

quality = pd.read_csv("RED WINE QUALITY DATASET.csv")
pd.options.display.max_columns = None
display(quality)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25,67,0.9968,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15,54,0.9970,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17,60,0.9980,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
194,7.6,0.550,0.21,2.2,0.071,7,28,0.9964,3.28,0.55,9.7,5
195,7.8,0.590,0.33,2.0,0.074,24,120,0.9968,3.25,0.54,9.4,5
196,7.3,0.580,0.30,2.4,0.074,15,55,0.9968,3.46,0.59,10.2,5
197,11.5,0.300,0.60,2.0,0.067,12,27,0.9981,3.11,0.97,10.1,6
198,5.4,0.835,0.08,1.2,0.046,13,93,0.9924,3.57,0.85,13.0,7